set unstable

DIR := if os() == "macos" { "mac" } else { "linux" }
PWD := absolute_path(".")

# Display this help
default:
  @just --list --unsorted

# Create symlinks, folders
setup:
  ln -sf {{PWD}}/config "$HOME/.zshrc"

# Install ZSH plugins
install-plugins: setup
  #!/usr/bin/env zsh
  echo "Installing shell plugins"
  ZSH="${ZSH:-$HOME/.oh-my-zsh}"
  if [ ! -d "${ZSH}/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH}/plugins/zsh-autosuggestions"
  else
    echo "zsh-autosuggestions already installed"
  fi

  if [ ! -d "${ZSH}/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH}/plugins/zsh-syntax-highlighting"
  else
    echo "zsh-syntax-highlighting already installed"
  fi

  if [ ! -d "${ZSH}/plugins/zsh-vi-mode" ]; then
    git clone https://github.com/jeffreytse/zsh-vi-mode "${ZSH}/plugins/zsh-vi-mode"
  else
    echo "zsh-vi-mode already installed"
  fi

  if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  else
    echo "tmux plugin manager already installed"
  fi


