set unstable

DIR := if os() == "macos" { "mac" } else { "linux" }
PWD := absolute_path(".")

# Display this help
default:
  @just --list --unsorted

# Create symlinks, folders
setup:
  ln -sf {{PWD}}/config "$HOME/.zshrc"

# Install ZSH plugins + spaceship theme
install-plugins: setup
  #!/usr/bin/env zsh
  echo "Installing shell plugins"
  ZSH="${ZSH:-$HOME/.oh-my-zsh}"

  # zsh-autosuggestions
  if [ ! -d "${ZSH}/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH}/plugins/zsh-autosuggestions"
  else
    echo "zsh-autosuggestions already installed"
  fi

  # zsh-syntax-highlighting
  if [ ! -d "${ZSH}/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH}/plugins/zsh-syntax-highlighting"
  else
    echo "zsh-syntax-highlighting already installed"
  fi

  # zsh-vi-mode
  if [ ! -d "${ZSH}/plugins/zsh-vi-mode" ]; then
    git clone https://github.com/jeffreytse/zsh-vi-mode "${ZSH}/plugins/zsh-vi-mode"
  else
    echo "zsh-vi-mode already installed"
  fi

  # spaceship-prompt theme
  if [ ! -d "${ZSH}/custom/themes/spaceship-prompt" ]; then
    git clone https://github.com/spaceship-prompt/spaceship-prompt.git \
      "${ZSH}/custom/themes/spaceship-prompt" --depth=1
    ln -sf "${ZSH}/custom/themes/spaceship-prompt/spaceship.zsh-theme" \
      "${ZSH}/custom/themes/spaceship.zsh-theme"
    echo "spaceship-prompt installed"
  else
    echo "spaceship-prompt already installed"
  fi

  # tmux plugin manager
  if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  else
    echo "tmux plugin manager already installed"
  fi

